version: '2'
networks:
  openvpn:
    name: openvpn
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.192.0/20
          gateway: 192.168.192.1
  research_network:
    name: research_network
volumes:
  research-data:
    name: research-data
  uploads:
    name: research_uploads
  storage-uploads:
    name: research_storage-uploads

services:
  openvpn:
    container_name: openvpn_server
    image: kylemanna/openvpn
    cap_add:
     - NET_ADMIN
    ports:
     - "4223:1194/udp"
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    networks:
      openvpn:
        ipv4_address: 192.168.192.2

  salt:
    container_name: salt
    image: salt:latest
    depends_on:
      - research_DB
    restart: always
    environment:
      - APP_HOST=<app_hostname>
      - APP_PORT=<app_port>
    networks:
      research_network:
      openvpn:
          ipv4_address: 192.168.192.3